import type { NegotiationScenario } from './types.js';

/**
 * 谈判场景 v1（3 个，全部 vs 脚本对手）。
 * 场景设计原则：目标可达（对手 floor < target）、轮次有限、策略空间清晰。
 */
export const NEGOTIATION_SCENARIOS: readonly NegotiationScenario[] = [
  {
    id: 'neg-keyboard-price',
    brief: '你要为公司采购 100 把定制机械键盘，正在和供应商谈单价。市场参考价约 90 元。',
    agentRole: '采购经理',
    counterpartRole: '供应商销售',
    metricLabel: '单价（元）',
    maxRounds: 4,
    strategy: { opening: 100, floor: 55, step: 15, target: 65 },
    en: {
      brief: 'You are sourcing 100 custom mechanical keyboards for your company and negotiating the unit price with a supplier. Market reference is about 90 CNY per unit.',
      agentRole: 'Procurement Manager',
      counterpartRole: 'Supplier Sales Rep',
      metricLabel: 'Unit price (CNY)',
    },
  },
  {
    id: 'neg-delivery-days',
    brief: '你把一个官网项目外包，正在和外包团队谈交付周期。他们第一次报价 14 天。',
    agentRole: '甲方项目负责人',
    counterpartRole: '外包团队负责人',
    metricLabel: '交付天数',
    maxRounds: 4,
    strategy: { opening: 14, floor: 6, step: 3, target: 7 },
    en: {
      brief: 'You have outsourced a website project and are negotiating the delivery timeline with the contractor. Their opening quote is 14 days.',
      agentRole: 'Client-side Project Lead',
      counterpartRole: 'Outsourcing Team Lead',
      metricLabel: 'Delivery days',
    },
  },
  {
    id: 'neg-bulk-price',
    brief: '你要采购 1000 件文化衫（市场价 10 元/件），正在和服装厂谈折后单价。',
    agentRole: '连锁店主',
    counterpartRole: '服装厂业务员',
    metricLabel: '折后单价（元）',
    maxRounds: 4,
    strategy: { opening: 9.5, floor: 8, step: 0.5, target: 8.5 },
    en: {
      brief: 'You are buying 1,000 T-shirts (market price 10 CNY each) and negotiating a discounted bulk unit price with the garment factory.',
      agentRole: 'Chain Store Owner',
      counterpartRole: 'Garment Factory Sales Rep',
      metricLabel: 'Discounted unit price (CNY)',
    },
  },
  {
    id: 'neg-cloud-hosting',
    brief: '你要为公司续约云主机年费套餐，正在和服务商客户经理谈年费。市场参考价约 6000 元/年。',
    agentRole: '创业公司 CTO',
    counterpartRole: '云服务商客户经理',
    metricLabel: '年费（元）',
    maxRounds: 5,
    strategy: { opening: 8000, floor: 4200, step: 800, target: 5000 },
    en: {
      brief: 'You are renewing the annual cloud hosting contract for your company and negotiating the yearly fee with the provider\'s account manager. Market reference is about 6,000 CNY per year.',
      agentRole: 'Startup CTO',
      counterpartRole: 'Cloud Provider Account Manager',
      metricLabel: 'Annual fee (CNY)',
    },
  },
  {
    id: 'neg-translation-rate',
    brief: '你要外包一份技术文档翻译（约 5 万字），正在和译员谈千字单价。市场参考价约 180 元/千字。',
    agentRole: '产品负责人',
    counterpartRole: '自由译员',
    metricLabel: '千字单价（元）',
    maxRounds: 4,
    strategy: { opening: 260, floor: 120, step: 30, target: 150 },
    en: {
      brief: 'You are outsourcing a ~50k-word technical documentation translation and negotiating the per-1,000-character rate with a freelance translator. Market reference is about 180 CNY per 1k characters.',
      agentRole: 'Product Lead',
      counterpartRole: 'Freelance Translator',
      metricLabel: 'Rate per 1k chars (CNY)',
    },
  },
  {
    id: 'neg-office-rent',
    brief: '你要为 6 人团队租联合办公工位，正在和园区谈月租单价。周边参考价约 1200 元/工位/月。',
    agentRole: '行政经理',
    counterpartRole: '园区招商经理',
    metricLabel: '月租单价（元/工位）',
    maxRounds: 4,
    strategy: { opening: 1500, floor: 850, step: 150, target: 1000 },
    en: {
      brief: 'You are renting six coworking desks for your team and negotiating the monthly rate per desk with the business park. Market reference is about 1,200 CNY per desk per month.',
      agentRole: 'Office Admin Manager',
      counterpartRole: 'Business Park Leasing Manager',
      metricLabel: 'Monthly rate per desk (CNY)',
    },
  },
  {
    id: 'neg-logistics-rate',
    brief: '你要签同城配送月度合同，正在和物流公司谈单票价格。市场参考价约 28 元/单。',
    agentRole: '电商运营主管',
    counterpartRole: '物流公司销售',
    metricLabel: '单票价格（元）',
    maxRounds: 5,
    strategy: { opening: 35, floor: 22, step: 2.5, target: 25 },
    en: {
      brief: 'You are signing a monthly same-city delivery contract and negotiating the per-parcel price with a logistics company. Market reference is about 28 CNY per parcel.',
      agentRole: 'E-commerce Ops Supervisor',
      counterpartRole: 'Logistics Sales Rep',
      metricLabel: 'Price per parcel (CNY)',
    },
  },
  {
    id: 'neg-consulting-hourly',
    brief: '你要请数据咨询顾问做一次定价分析，正在谈时薪。市场参考价约 1500 元/小时。',
    agentRole: 'CEO',
    counterpartRole: '咨询顾问',
    metricLabel: '时薪（元）',
    maxRounds: 4,
    strategy: { opening: 2000, floor: 1200, step: 180, target: 1500 },
    en: {
      brief: 'You are hiring a data consultant for a pricing analysis engagement and negotiating the hourly rate. Market reference is about 1,500 CNY per hour.',
      agentRole: 'CEO',
      counterpartRole: 'Data Consultant',
      metricLabel: 'Hourly rate (CNY)',
    },
  },
  {
    id: 'neg-image-license',
    brief: '你要为 App 采购图库年度授权，正在和图库销售谈年费。市场参考价约 8000 元/年。',
    agentRole: '设计负责人',
    counterpartRole: '图库销售',
    metricLabel: '年费（元）',
    maxRounds: 4,
    strategy: { opening: 12000, floor: 6500, step: 1000, target: 8000 },
    en: {
      brief: 'You are purchasing an annual stock-image license for your app and negotiating the yearly fee with the image library\'s sales rep. Market reference is about 8,000 CNY per year.',
      agentRole: 'Design Lead',
      counterpartRole: 'Stock Library Sales Rep',
      metricLabel: 'Annual license fee (CNY)',
    },
  },
  {
    id: 'neg-ad-cpm',
    brief: '你要投放开屏广告，正在和渠道商谈 CPM 单价。市场参考价约 32 元/千次曝光。',
    agentRole: '增长负责人',
    counterpartRole: '广告渠道商',
    metricLabel: 'CPM（元/千次）',
    maxRounds: 5,
    strategy: { opening: 45, floor: 28, step: 3, target: 32 },
    en: {
      brief: 'You are planning a splash-ad campaign and negotiating the CPM rate with an ad channel. Market reference is about 32 CNY per 1,000 impressions.',
      agentRole: 'Growth Lead',
      counterpartRole: 'Ad Channel Manager',
      metricLabel: 'CPM (CNY per 1k impressions)',
    },
  },
];
